openapi: 3.0.3

info:
  title: Banking API
  version: 1.0.0

servers:
  - url: https://api.bank.local

paths:

  /api/v1/auth/login:
    post:
      summary: Login

  /api/v1/accounts/{id}/balance:
    get:
      security:
        - BearerAuth: []

  /api/v1/accounts/{id}/transactions:
    get:
      security:
        - BearerAuth: []

  /api/v1/transfers:
    post:
      security:
        - BearerAuth: []

components:
  securitySchemes:

    BearerAuth:

      type: http

      scheme: bearer

      bearerFormat: JWT